services:
  - type: web
    name: kiosk-api
    runtime: docker
    rootDir: backend
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: DB_CONNECTION
        value: pgsql
      - key: APP_KEY
        sync: false # You will set this in the UI
      - key: DB_HOST
        sync: false # You will set this in the UI
      - key: DB_PORT
        sync: false # You will set this to 6543 in the UI
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        sync: false # You will set this to postgres.xxxx in the UI
      - key: DB_PASSWORD
        sync: false # You will set this in the UI
